name: Daily Open PR Sync

# For testing
# on: push

# For prod
on:
  schedule:
    - cron: "37 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build

      # Go through all open PRs and run the bot over them
      - run: node ./bin/run.js
        env:
          BOT_AUTH_TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}
