name: Daily Open PR Sync

on:
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      - run: pnpm install
      - run: pnpm run build

      # Go through all open PRs and run the bot over them
      - run: node ./dist/run.js
        env:
          BOT_AUTH_TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}
